/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef PHP_WOLFSSL_H
#define PHP_WOLFSSL_H

extern zend_module_entry wolfssl_module_entry;
#define phpext_wolfssl_ptr &wolfssl_module_entry

#ifdef PHP_WIN32
# define PHP_WOLFSSL_API __declspec(dllexport)
#else
# define PHP_WOLFSSL_API
#endif

ZEND_NAMED_FUNCTION(_wrap_wolfSSLv23_client_method);
ZEND_NAMED_FUNCTION(_wrap_wolfSSLv23_server_method);
ZEND_NAMED_FUNCTION(_wrap_wolfSSL_CTX_new);
ZEND_NAMED_FUNCTION(_wrap_wolfSSL_CTX_load_verify_locations);
ZEND_NAMED_FUNCTION(_wrap_wolfSSL_new);
ZEND_NAMED_FUNCTION(_wrap_wolfSSL_get_error);
ZEND_NAMED_FUNCTION(_wrap_wolfSSL_write);
ZEND_NAMED_FUNCTION(_wrap_wolfSSL_Debugging_ON);
ZEND_NAMED_FUNCTION(_wrap_wolfSSL_Init);
ZEND_NAMED_FUNCTION(_wrap_wolfSSL_use_certificate_buffer);
ZEND_NAMED_FUNCTION(_wrap_wolfSSL_use_PrivateKey_buffer);
ZEND_NAMED_FUNCTION(_wrap_ProcessBuffer);
ZEND_NAMED_FUNCTION(_wrap_wc_SignatureGenerate);
ZEND_NAMED_FUNCTION(_wrap_wc_PKCS12_PBKDF);
ZEND_NAMED_FUNCTION(_wrap_wc_RsaSSL_Sign);
ZEND_NAMED_FUNCTION(_wrap_wc_RsaSSL_Verify);
PHP_MINIT_FUNCTION(wolfssl);

#endif /* PHP_WOLFSSL_H */
